"""Tests for src/notify.py — Telegram HTML conversion and report splitting."""

from __future__ import annotations

import urllib.error
import urllib.request
from types import SimpleNamespace
from unittest.mock import patch

import pytest

from cmd_llm_common import telegram_chat_id
from config import TELEGRAM_SEND_RETRY_DELAYS
from notify import (
    md_to_telegram_html,
    send_telegram,
    send_telegram_photo,
    split_report_sections,
    urlopen_retrying,
)


class TestMdToTelegramHtmlHeaders:
    def test_h1(self) -> None:
        assert md_to_telegram_html("# Hello") == "<b>Hello</b>"

    def test_h2(self) -> None:
        assert md_to_telegram_html("## Section") == "<b>Section</b>"

    def test_h3(self) -> None:
        assert md_to_telegram_html("### Sub") == "<b>Sub</b>"

    def test_header_with_inline_bold(self) -> None:
        assert md_to_telegram_html("## **Week** Review") == "<b><b>Week</b> Review</b>"


class TestMdToTelegramHtmlInline:
    def test_bold_asterisks(self) -> None:
        assert md_to_telegram_html("**bold**") == "<b>bold</b>"

    def test_bold_underscores(self) -> None:
        assert md_to_telegram_html("__bold__") == "<b>bold</b>"

    def test_italic_asterisks(self) -> None:
        assert md_to_telegram_html("*italic*") == "<i>italic</i>"

    def test_italic_underscores(self) -> None:
        assert md_to_telegram_html("_italic_") == "<i>italic</i>"

    def test_inline_code(self) -> None:
        assert md_to_telegram_html("`code`") == "<code>code</code>"

    def test_mixed_bold_and_italic(self) -> None:
        result = md_to_telegram_html("**bold** and *italic*")
        assert "<b>bold</b>" in result
        assert "<i>italic</i>" in result

    def test_inline_code_not_formatted_inside(self) -> None:
        result = md_to_telegram_html("`**not bold**`")
        assert "<b>" not in result
        assert "<code>**not bold**</code>" in result


class TestMdToTelegramHtmlLists:
    def test_unordered_dash(self) -> None:
        assert md_to_telegram_html("- item one") == "  • item one"

    def test_unordered_asterisk(self) -> None:
        assert md_to_telegram_html("* item two") == "  • item two"

    def test_ordered(self) -> None:
        assert md_to_telegram_html("1. first") == "  1. first"

    def test_list_with_bold(self) -> None:
        assert md_to_telegram_html("- **key**: value") == "  • <b>key</b>: value"


class TestMdToTelegramHtmlCodeBlocks:
    def test_fenced_code_block(self) -> None:
        md = "```\nprint('hi')\n```"
        result = md_to_telegram_html(md)
        assert "<pre>" in result
        assert "print(&#x27;hi&#x27;)" in result or "print(&#39;hi&#39;)" in result

    def test_fenced_code_block_with_language(self) -> None:
        md = "```python\nx = 1\n```"
        result = md_to_telegram_html(md)
        assert '<code class="language-python">' in result

    def test_unclosed_code_block(self) -> None:
        md = "```\nsome code"
        result = md_to_telegram_html(md)
        assert "<pre>" in result


class TestMdToTelegramHtmlMisc:
    def test_horizontal_rule(self) -> None:
        assert md_to_telegram_html("---") == "───────"
        assert md_to_telegram_html("***") == "───────"

    def test_blockquote(self) -> None:
        result = md_to_telegram_html("> quoted text")
        assert "<blockquote>quoted text</blockquote>" in result

    def test_html_entities_escaped(self) -> None:
        result = md_to_telegram_html("1 < 2 & 3 > 0")
        assert "&lt;" in result
        assert "&amp;" in result
        assert "&gt;" in result

    def test_link(self) -> None:
        result = md_to_telegram_html("[click](https://example.com)")
        assert '<a href="https://example.com">click</a>' in result

    def test_empty_input(self) -> None:
        assert md_to_telegram_html("") == ""

    def test_plain_text_passthrough(self) -> None:
        assert md_to_telegram_html("just text") == "just text"

    def test_multiline_report(self) -> None:
        md = "# Week Review\n\n**Steps**: 52k\n\n- Good sleep\n- Low HRV"
        result = md_to_telegram_html(md)
        assert "<b>Week Review</b>" in result
        assert "<b>Steps</b>: 52k" in result
        assert "• Good sleep" in result
        assert "• Low HRV" in result
        assert "Generated by" not in result


class TestSplitReportSections:
    def test_single_section(self) -> None:
        md = "## Only Section\n\nSome content here."
        sections = split_report_sections(md)
        assert len(sections) == 1
        assert "## Only Section" in sections[0]

    def test_title_plus_sections(self) -> None:
        md = (
            "# W12 Review\n\n"
            "## Week at a Glance\n\nGood week.\n\n"
            "## Key Metrics\n\nHRV stable."
        )
        sections = split_report_sections(md)
        assert len(sections) == 3
        assert "# W12 Review" in sections[0]
        assert "## Week at a Glance" in sections[1]
        assert "## Key Metrics" in sections[2]

    def test_empty_input(self) -> None:
        assert split_report_sections("") == []

    def test_no_headers(self) -> None:
        md = "Just some text without headers."
        sections = split_report_sections(md)
        assert len(sections) == 1
        assert "Just some text" in sections[0]

    def test_sections_preserve_content(self) -> None:
        md = (
            "## Training Review\n\n"
            "Day 1: Run\nDay 2: Rest\n\n"
            "## Recovery\n\nReady to push."
        )
        sections = split_report_sections(md)
        assert len(sections) == 2
        assert "Day 1: Run" in sections[0]
        assert "Day 2: Rest" in sections[0]
        assert "Ready to push." in sections[1]


class TestTelegramDestinationGuard:
    """A run without a roster entry must not POST an empty chat_id.

    Regression: `--db PATH` resolves no profile, so `args.telegram_id` is
    unset. The chat_id guard was dropped during the multi-profile split and
    `--telegram` started posting `chat_id: ""` to the Telegram API.
    """

    @pytest.mark.parametrize("chat_id", [None, "", "None"])
    def test_send_telegram_refuses_missing_destination(
        self, chat_id, monkeypatch, caplog
    ) -> None:
        monkeypatch.setenv("TELEGRAM_BOT_TOKEN", "fake-token")
        with patch("urllib.request.urlopen") as mock_urlopen:
            result = send_telegram("report", "W01", chat_id=chat_id)

        assert result is None
        mock_urlopen.assert_not_called()
        assert "--profile" in caplog.text

    @pytest.mark.parametrize("chat_id", [None, "", "None"])
    def test_send_telegram_photo_refuses_missing_destination(
        self, chat_id, monkeypatch
    ) -> None:
        monkeypatch.setenv("TELEGRAM_BOT_TOKEN", "fake-token")
        with patch("urllib.request.urlopen") as mock_urlopen:
            assert send_telegram_photo(b"png", chat_id=chat_id) is False
        mock_urlopen.assert_not_called()

    def test_send_telegram_photo_refuses_even_with_explicit_token(self) -> None:
        with patch("urllib.request.urlopen") as mock_urlopen:
            assert (
                send_telegram_photo(b"png", bot_token="explicit", chat_id=None) is False
            )
        mock_urlopen.assert_not_called()


class TestMessageEffectNeverCostsTheMessage:
    """Regression: a refused effect used to lose the whole nudge.

    The effect was carried into the plain-text fallback, so a well-formed but
    unknown effect id made Telegram refuse both attempts and the nudge was
    dropped. Proven against the live API before the fix: two 400s, no message.
    An effect is decoration; the message is not.
    """

    def _responses(self, *outcomes):
        """Build urlopen side effects from 'refuse' / 'ok' outcomes."""
        sent: list[dict] = []

        def _fake(req, *args, **kwargs):
            import json

            sent.append(json.loads(req.data.decode()))
            outcome = outcomes[len(sent) - 1]
            if outcome == "refuse":
                raise urllib.error.HTTPError(
                    "url",
                    400,
                    "Bad Request",
                    {},
                    None,  # type: ignore[arg-type]
                )

            class _Resp:
                def __enter__(self_inner):
                    return self_inner

                def __exit__(self_inner, *exc):
                    return False

                def read(self_inner):
                    return json.dumps(
                        {"ok": True, "result": {"message_id": 7}}
                    ).encode()

            return _Resp()

        return _fake, sent

    def test_a_refused_effect_is_dropped_and_the_message_still_lands(
        self, monkeypatch
    ) -> None:
        monkeypatch.setenv("TELEGRAM_BOT_TOKEN", "fake-token")
        fake, sent = self._responses("refuse", "ok")
        with patch("urllib.request.urlopen", side_effect=fake):
            result = send_telegram(
                "**hi**", "W01", chat_id="123", message_effect_id="9999"
            )

        assert result == 7
        assert len(sent) == 2
        assert sent[0]["message_effect_id"] == "9999"
        # The retry keeps the formatting and sheds only the animation.
        assert "message_effect_id" not in sent[1]
        assert sent[1]["parse_mode"] == "HTML"

    def test_bad_markup_still_falls_through_to_plain_text(self, monkeypatch) -> None:
        monkeypatch.setenv("TELEGRAM_BOT_TOKEN", "fake-token")
        fake, sent = self._responses("refuse", "refuse", "ok")
        with patch("urllib.request.urlopen", side_effect=fake):
            result = send_telegram(
                "**hi**", "W01", chat_id="123", message_effect_id="9999"
            )

        assert result == 7
        assert len(sent) == 3
        assert "parse_mode" not in sent[2]
        assert "message_effect_id" not in sent[2]

    def test_no_effect_means_no_extra_attempt(self, monkeypatch) -> None:
        monkeypatch.setenv("TELEGRAM_BOT_TOKEN", "fake-token")
        fake, sent = self._responses("ok")
        with patch("urllib.request.urlopen", side_effect=fake):
            assert send_telegram("hi", "W01", chat_id="123") == 7
        assert len(sent) == 1


class TestTelegramChatId:
    def test_returns_none_without_a_resolved_profile(self) -> None:
        assert telegram_chat_id(SimpleNamespace()) is None
        assert telegram_chat_id(SimpleNamespace(telegram_id=None)) is None

    def test_stringifies_a_numeric_roster_id(self) -> None:
        assert telegram_chat_id(SimpleNamespace(telegram_id=12345)) == "12345"


class TestUrlopenRetrying:
    """Telegram sends must survive a passing transport fault.

    Every send used to be a single attempt: one dropped socket and the message
    was gone, with the caller returning None and no trace beyond a log line.
    That is how a data-sync alert about three days of missing uploads was
    itself lost on 2 Sep 2026.
    """

    def _request(self) -> urllib.request.Request:
        return urllib.request.Request("https://api.telegram.org/botX/sendMessage")

    @patch("notify.time.sleep")
    @patch("notify.urllib.request.urlopen")
    def test_succeeds_without_sleeping(self, mock_open, mock_sleep) -> None:
        mock_open.return_value = "response"
        assert urlopen_retrying(self._request(), what="sendMessage") == "response"
        mock_sleep.assert_not_called()

    @patch("notify.time.sleep")
    @patch("notify.urllib.request.urlopen")
    def test_retries_a_dropped_socket(self, mock_open, mock_sleep) -> None:
        mock_open.side_effect = [
            OSError(49, "Can't assign requested address"),
            "response",
        ]
        assert urlopen_retrying(self._request(), what="sendMessage") == "response"
        assert mock_open.call_count == 2
        mock_sleep.assert_called_once_with(TELEGRAM_SEND_RETRY_DELAYS[0])

    @patch("notify.time.sleep")
    @patch("notify.urllib.request.urlopen")
    def test_backs_off_across_the_full_ladder(self, mock_open, mock_sleep) -> None:
        mock_open.side_effect = OSError(49, "Can't assign requested address")
        with pytest.raises(OSError):
            urlopen_retrying(self._request(), what="sendMessage")
        assert mock_open.call_count == len(TELEGRAM_SEND_RETRY_DELAYS) + 1
        assert [c.args[0] for c in mock_sleep.call_args_list] == list(
            TELEGRAM_SEND_RETRY_DELAYS
        )

    @patch("notify.time.sleep")
    @patch("notify.urllib.request.urlopen")
    def test_http_error_is_not_retried(self, mock_open, mock_sleep) -> None:
        """Telegram answered and declined.

        Retrying will not change its mind, and send_reply depends on seeing it
        at once to fall back from HTML to plain text.
        """
        mock_open.side_effect = urllib.error.HTTPError(
            "url", 400, "Bad Request", {}, None
        )
        with pytest.raises(urllib.error.HTTPError):
            urlopen_retrying(self._request(), what="sendMessage")
        assert mock_open.call_count == 1
        mock_sleep.assert_not_called()
