"""Tests for src/notify.py — Telegram HTML conversion."""

from __future__ import annotations

from notify import md_to_telegram_html


class TestMdToTelegramHtmlHeaders:
    def test_h1(self) -> None:
        assert md_to_telegram_html("# Hello") == "<b>Hello</b>"

    def test_h2(self) -> None:
        assert md_to_telegram_html("## Section") == "<b>Section</b>"

    def test_h3(self) -> None:
        assert md_to_telegram_html("### Sub") == "<b>Sub</b>"

    def test_header_with_inline_bold(self) -> None:
        assert md_to_telegram_html("## **Week** Review") == "<b><b>Week</b> Review</b>"


class TestMdToTelegramHtmlInline:
    def test_bold_asterisks(self) -> None:
        assert md_to_telegram_html("**bold**") == "<b>bold</b>"

    def test_bold_underscores(self) -> None:
        assert md_to_telegram_html("__bold__") == "<b>bold</b>"

    def test_italic_asterisks(self) -> None:
        assert md_to_telegram_html("*italic*") == "<i>italic</i>"

    def test_italic_underscores(self) -> None:
        assert md_to_telegram_html("_italic_") == "<i>italic</i>"

    def test_inline_code(self) -> None:
        assert md_to_telegram_html("`code`") == "<code>code</code>"

    def test_mixed_bold_and_italic(self) -> None:
        result = md_to_telegram_html("**bold** and *italic*")
        assert "<b>bold</b>" in result
        assert "<i>italic</i>" in result

    def test_inline_code_not_formatted_inside(self) -> None:
        result = md_to_telegram_html("`**not bold**`")
        assert "<b>" not in result
        assert "<code>**not bold**</code>" in result


class TestMdToTelegramHtmlLists:
    def test_unordered_dash(self) -> None:
        assert md_to_telegram_html("- item one") == "  • item one"

    def test_unordered_asterisk(self) -> None:
        assert md_to_telegram_html("* item two") == "  • item two"

    def test_ordered(self) -> None:
        assert md_to_telegram_html("1. first") == "  1. first"

    def test_list_with_bold(self) -> None:
        assert md_to_telegram_html("- **key**: value") == "  • <b>key</b>: value"


class TestMdToTelegramHtmlCodeBlocks:
    def test_fenced_code_block(self) -> None:
        md = "```\nprint('hi')\n```"
        result = md_to_telegram_html(md)
        assert "<pre>" in result
        assert "print(&#x27;hi&#x27;)" in result or "print(&#39;hi&#39;)" in result

    def test_fenced_code_block_with_language(self) -> None:
        md = "```python\nx = 1\n```"
        result = md_to_telegram_html(md)
        assert '<code class="language-python">' in result

    def test_unclosed_code_block(self) -> None:
        md = "```\nsome code"
        result = md_to_telegram_html(md)
        assert "<pre>" in result


class TestMdToTelegramHtmlMisc:
    def test_horizontal_rule(self) -> None:
        assert md_to_telegram_html("---") == "───────"
        assert md_to_telegram_html("***") == "───────"

    def test_blockquote(self) -> None:
        result = md_to_telegram_html("> quoted text")
        assert "<blockquote>quoted text</blockquote>" in result

    def test_html_entities_escaped(self) -> None:
        result = md_to_telegram_html("1 < 2 & 3 > 0")
        assert "&lt;" in result
        assert "&amp;" in result
        assert "&gt;" in result

    def test_link(self) -> None:
        result = md_to_telegram_html("[click](https://example.com)")
        assert '<a href="https://example.com">click</a>' in result

    def test_empty_input(self) -> None:
        assert md_to_telegram_html("") == ""

    def test_plain_text_passthrough(self) -> None:
        assert md_to_telegram_html("just text") == "just text"

    def test_multiline_report(self) -> None:
        md = "# Week Review\n\n**Steps**: 52k\n\n- Good sleep\n- Low HRV\n\n---\n_Generated by model_"
        result = md_to_telegram_html(md)
        assert "<b>Week Review</b>" in result
        assert "<b>Steps</b>: 52k" in result
        assert "• Good sleep" in result
        assert "• Low HRV" in result
        assert "───────" in result
        assert "<i>Generated by model</i>" in result
